### ISSUE TITLE
Chapter 6 Shrine scene - unable to continue

### ISSUE THREAD

**Issue by EvilDude** [higurashi-mod/watanagashi#10]
During the scene where Keiichi is relaxing after the shrine prep work and Shion turns up to hand a drink the screen goes dark as part of the scene but will not continue. Clicking or skipping appear to do nothing, menu does not appear, though the exit confirmation dialog will. Restarting the game does not resolve it.
Seems to be similar to the issue reported in the thread (14350291)

Github doesn't seem to like the zip with my save so: https://mega.nz/#!6JR2hAxZ!cdBZNk2ph6TvsjrQKepFZ8dPVTt0HnKdnztxPpQbMqQ

**Comment by ErisKyn** [comment]
I downloaded your save, I don't see anything wrong with chapter 6.

Which exact part of the dialogue is giving you trouble?

Also, try deleting wata_007.mg in both CompiledScripts and CompiledUpdateScripts folders and see if that changes anything.

**Comment by ItaloKnox** [comment]
Somehow Mega is not opening here. Can you tell me the exact last line of dialog before it stops working?

**Comment by EvilDude** [comment]
![higurashi_chapter6_shrine_scene](https://cloud.githubusercontent.com/assets/16456745/12041120/cdee8050-ae6e-11e5-8d72-58c9e6e4e286.gif)
[higurashi02.zip](https://github.com/higurashi-mod/watanagashi/files/74313/higurashi02.zip)

Deleting the files does not seem to make a difference

Uploaded my save files zip here now, I made a save closer to the point where it gets stuck. Also added a gif showing the issue.

Last lines:

"Kei-chan, great work! Here's some tea for you."
"You're so considerate~! Thanks Mi-"
Her voice sounded exactly the same, but it somehow felt different.

"Wait, you're...!!"
[Fade to black and change of music]

**Comment by ItaloKnox** [comment]
I don't know what exactly is wrong with your game, but your save works fine here. Also double-checked the script and there was nothing wrong with it. The previous error was related to some lines without quotes, this scene looks fine.

![higurashi_when_they_cry_-_ch 2_watanagashi_2015-12-29_19-23-11](https://cloud.githubusercontent.com/assets/4702556/12042385/b2084680-ae61-11e5-9f39-6c5cac527252.png)

**Comment by Offlien** [comment]
I'm having the same problem as OP/EvilDude, the game stops for me at that exact line. I only have the watanagashi voice patch (most recent, 0.5.1) installed, and HigurashiPS3Voices 1 and 2 (corresponding files, s2/s19/s20) installed. Not sure if it has to do with me not having the graphics mod installed like the post above does, but just thought that I would note that.

**Comment by ItaloKnox** [comment]
This patch was built to be used with both voices and graphics. There's a voice-only patch in the repository, [here](https://github.com/higurashi-mod/watanagashi/tree/master/dev/Update%20%28voice%20only%29).

There's a few things to fix but nothing I can't do in a few hours.

**Comment by Offlien** [comment]
Ah, didn't know I had to have graphics installed too.
I'm already in the process of downloading the graphics but in the meantime I'll just try out the voice patch one. Excuse my ignorance, but how can I download those files from the page you gave me? I'm a bit new to this site and while I've managed a bit in the past, I simply can't figure it out this time...

**Comment by EvilDude** [comment]
I also did not have the graphics installed either, installing it solves the issue. So I assume I can either keep playing with the graphics mod or wait for the voice only patch to be fixed?

In any case thanks for the effort, sorry for having to go through the trouble when the issue was on my end.

Offlien, if you go to the master page (https://github.com/higurashi-mod/watanagashi) there's a download zip button, though it downloads the whole thing.

**Comment by ItaloKnox** [comment]
@Offlien 
Currently the only way of getting the voice only patch is downloading the whole repository. You can either clone it or download the master file as EvilDude explained.

@EvilDude 
The voice only patch is not "officially" supported. It's hard to track all changes and keep both versions updated. We usually drop the voice only patch after all scripts get fixed and merged with the graphics patch, but I choose to keep it this time. That's why it's in the dev folder.

I suggest playing with the graphics patch installed. You'll lose the new Steam sprites but you get a lot of cool stuff using it. It's a fair trade.

**Comment by EvilDude** [comment]
Alright, I'll do that then, indeed a minor thing given the effort put into this.

Thanks again all.
