### ISSUE TITLE
White artifacting around scenario text

### ISSUE THREAD

**Issue by drojf** [higurashi-mod/watanagashi#109]
I noticed there was this white artifacting around the text displayed before you start the game (click to view fullsize):

![Capture](https://user-images.githubusercontent.com/1249449/100828829-238af900-34b4-11eb-9b8e-7f1dab9c999f.PNG)

I previously saw this issue with the italian translation's image assets, and fixed the issue by running the images through `pngrim` (if you want a binary for `pngrim`, you can download it here: https://github.com/drojf/pngrim/releases/tag/v1.0.0). 

You can read about what causes this issue here: [http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/](http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/). In short, if the transparent pixels near the edge of an image don't match the color of the non-transparent pixels, you'll get this kind of artifacting ~~with programs which use premultiplied alpha (premultiplied alpha is commonly used in games).~~ with programs which both use straight alpha and also use a form of texture filtering which produces artifacts during transforms (GPU image scaling etc. used in games can cause this).

Here are the fixed image assets, run through .pngrim (probably not all of them have the problem, but I ran pngrim through them anyway):

[wata_scenario_text_white_artifact_fix_2020-12-02.zip](https://github.com/07th-mod/watanagashi/files/5627005/wata_scenario_text_white_artifact_fix_2020-12-02.zip)

I haven't checked the other chapters for this issue, only Watanagashi.

**Comment by enumag** [comment]
I would make no sense for this issue to exist only in watanagashi. It might be specific to some installations though, I don't think my wata installation is suffering from this. I'll check when I get home.

**Comment by TellowKrinkle** [comment]
> you'll get this kind of artifacting with programs which use premultiplied alpha

which *don't use premultiplied alpha

**Comment by drojf** [comment]
I'm not sure my understanding is correct - isn't the problem because the images are not created correctly for programs which use premultiplied alpha? 

As in, if Higurashi didn't use premultiplied alpha (if higurashi used straight alpha) it would display OK as it would display the same as it does in photoshop which uses straight alpha.

I guess I can't rule out there being another phenomenon causing this, though.

**Comment by drojf** [comment]
Actually, wait I think I get it - so the issue actually comes from the image being resized and the alpha channel also being resized (or the image not being at a integer pixel offset, other transforms etc.)....I guess I misinterpreted the the article when I read it, or I misremembered it as I read it quite a while ago....
