### ISSUE TITLE
Missing voices at the end of chapter 6 and onwards 

### ISSUE THREAD

**Issue by Kizul** [higurashi-mod/watanagashi#15]
I've just read til the end of chapter 6, and then at the start of the new chapter, no voices play. Thereafter, i skipped onwards to see if there were any voices playing at all in chapter 7 and discovered that it was not the case. Even at the start of chapter 8, there were still no voices coming out.

**Comment by ItaloKnox** [comment]
I looked around chapters 6~8 and they look fine. I can't see anything wrong with the scripts.
Can you reinstall the patch? Don't forget to delete the stuff inside CompiledUpdateScripts folder.

**Comment by Kizul** [comment]
ahaha, i found out what the problem is, it seems i forgot to get s02, and put it into SE. After i did that it all went smoothly. I am completly sorry for wasting your time, keep up the good work!
