### ISSUE TITLE
Graphics mod with Steam sprites

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/watanagashi#21]
Unlike Onikakushi there is no Graphics mod with Steam sprites instead of PS3 sprites.

I think it should work if I use the Graphics Mod with PS3 sprites but don't replace any of the existing files. Is there anything else I should do?

**Comment by ItaloKnox** [comment]
To be honest I don't have a clue because we're treating the patch like a full conversion. There's a lot of content here that is not present in the original game.

You have this option on Onikakushi because at that time we just planned to port the visual and voices, but since Onikakushi v2 we're translating and changing the script to play just like the PS3 game.

**Comment by enumag** [comment]
That's all fine I just like the new Steam sprites slightly better than the PS3 ones. (Sure enough Mion is awful in both cases.)

**Comment by ItaloKnox** [comment]
Maybe you can get it to work if you have **all** sprites matching the PS3 sprites. It'll crash if there is a missing sprite (or you can just ignore one or two exclusive PS3 sprites).

**Comment by enumag** [comment]
It seems there are quite a few PS3 sprites that don't have their steam equivalent. I'll just use the PS3 ones then. Thanks.

**Comment by enumag** [comment]
@ItaloKnox I really like the steam sprites more than the PS3 ones so I ended up updating the patch myself. There is one problem though. There are some weather-specific sprites in the sunset and night directories which have slightly different colors. Do you have any idea how I can convert the normal steam sprites to these weather specific ones?

There are some converted sprites in the old Onikakushi patch however Watanagashi-specific sprites are missing (of course) and also they were created before the last update from MangaGamer so they have lower resolution than the current Steam version. So I'd like to create new ones for Onikakushi as well.

**Comment by ItaloKnox** [comment]
Well, my work was completely unrelated to the graphics. Take a look at the Higurashi Steam forums, you'll find the GuraMan there, he's the guy responsible for the graphics mod.

**Comment by enumag** [comment]
Thanks, I'll try. http://steamcommunity.com/app/410890/discussions/0/490125737467552633/#p3
