### ISSUE TITLE
Sonozaki Oryo = Nana?

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/watanagashi#35]
Several times the old hag Oryo is referred to as "Nana" - why is that? I tried to google it but couldn't find anything.

**Comment by ItaloKnox** [comment]
Nana = grandma. Double check the script, most likely you'll see おばさん there.

**Comment by enumag** [comment]
Shouldn't it be "nana" instead of "Nana" then? I thought it was a name or something.

**Comment by enumag** [comment]
Also wouldn't it be better to simply use "grandma" as translation? I never heard the "nana" synonym until now.

**Comment by ItaloKnox** [comment]
It's just like mama or papa. Both cases aren't wrong, it's just a matter of which you prefer.

Can you show me the script/line where this happens? I want to check the japanese text.

**Comment by enumag** [comment]
I've found six places where it is used:
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_004.txt#L4635
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_009.txt#L2489
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_012_02.txt#L2982
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_012_02.txt#L4153
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_tips_16.txt#L171
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_tips_16.txt#L235

**Comment by enumag** [comment]
By the way is there a similar synonym for grandpa as well?

**Comment by ItaloKnox** [comment]
It's not おばさん as I expected but it's 婆っちゃ (babaccha: old lady + colloquialism) in all cases. That makes sense why it's nana instead of grandma.

I dunno about a similar thing for grandpa, probably there is one, though not really used. おじいちゃん is pretty much the standard, maybe there's a bit of cultural past on this.

**Comment by enumag** [comment]
Thanks for the explanation!
