### ISSUE TITLE
bg_154 blurry

### ISSUE THREAD

**Issue by Kamlingen** [higurashi-mod/watanagashi#48]
bg_154 is blurry, but that can be fixed by overwriting it with bg_155.

**Comment by ItaloKnox** [comment]
Can you upload this image here? Just don't put it on imgur or anything else, since they usually compress the image, just attach it here. Since it's just a single image, I can simply push a new version instead of updating the whole patch.

**Comment by Kamlingen** [comment]
https://mega.nz/#!wtxWkQbC!z0dNHYaw2lx1o-v72HpjdtX7HOMVJs86rx0lxUGg660
