### ISSUE TITLE
Wrong eyes CG

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/watanagashi#52]
@ItaloKnox Please replace cg_eye.png in our watanagashi graphics patch with this:

![cg_eye](https://cloud.githubusercontent.com/assets/539462/25772469/cc1c3c22-326b-11e7-836d-8f1728ec44bb.png)

**Comment by ItaloKnox** [comment]
Good, should be fixed now. 👍

**Comment by enumag** [comment]
@ItaloKnox Can you make the same change in Himatsu graphics patch? I only now noticed that it's used there as well.

**Comment by ItaloKnox** [comment]
Gotcha, updated and ready to go.
