### ISSUE TITLE
Installer doesn't put anything in CG

### ISSUE THREAD

**Issue by Kamlingen** [higurashi-mod/watanagashi#53]
![cmd](https://cloud.githubusercontent.com/assets/22724316/26043296/7035097a-393c-11e7-8396-9d31d32f5d57.png)

Line 39 .\7za.exe x watanagashi-graphics.zip

Guessing that this got the wrong name

**Comment by ItaloKnox** [comment]
You are correct, I just pushed a fix. Can't believe I forgot this one.

Thanks a lot for letting me know!
