### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Kamlingen** [higurashi-mod/watanagashi#55]
When I use the installer it's stops here and I have to manually decide if I want to replace the file. There is some files that shouldn't get replaced

ex_jump
ex_otsu_wata
title02

![w1](https://cloud.githubusercontent.com/assets/22724316/26222071/e99ed24e-3c18-11e7-8bd4-e204f4564f83.png)

**Comment by ItaloKnox** [comment]
Swapping the installation order will probably fix that, though I'm not sure how it found anything to overwrite. Don't you have any leftovers in the temp folder?

Edit: also pushed a new script with the order changed.

**Comment by Kamlingen** [comment]
Think the problem is that the .zip contains duplicate file names

**Comment by ItaloKnox** [comment]
I don't think so, the compiler exists so we can avoid duplicates.

![firefox_2017-05-18_17-53-19](https://cloud.githubusercontent.com/assets/4702556/26223071/f0a17018-3bf2-11e7-929b-84f37cffd353.png)

Give me some help here, @enumag

**Comment by Kamlingen** [comment]
![r2](https://cloud.githubusercontent.com/assets/22724316/26223177/48f00a8e-3c1d-11e7-92e8-d5bb1727b4f7.png)

**Comment by ItaloKnox** [comment]
Makes a lot of sense now, it's a Windows issue. Give me a couple of minutes to fix it.

**Comment by enumag** [comment]
Looks like I failed to fix all the case sensitivity issues in the patch. Just delete the duplicate files and I'll then recheck the case sensitivity when you're done.

EDIT: This issue probably applies to all chapters.

**Comment by enumag** [comment]
Also let me know which files you deleted please. I will not be able to fix the scripts otherwise.

**Comment by ItaloKnox** [comment]
Found four matches for this issue:
```
CG/title02.png
CG/Ex_otsu_wata.png
CG/Ex_Tips.png
CG/Ex_jump.png
```
There might be more. New zip is already uploaded.

**Comment by Kamlingen** [comment]
end_2

**Comment by ItaloKnox** [comment]
Is this the last one?

**Comment by Kamlingen** [comment]
Yes

**Comment by ItaloKnox** [comment]
Gotcha, compiled a new one and it's already uploaded. Thanks a lot, I'll leave this open just in case we find something else wrong.

**Comment by Kamlingen** [comment]
All the other have the same problem

Onikakushi
ex_jump
title02
ex_otsu
end_2
end_1
ex_tips

Tatarigoroshi
end_2
title02

Himatsubushi
end_2
end_1
title02

**Comment by ItaloKnox** [comment]
I guess computer code is just as human as we are. Sometimes I'm just glad I'm paying a private server just to finish this stuff quickly.

New builds should be up already, thanks a lot for finding these out.

**Comment by Kamlingen** [comment]
Tatarigoroshi
end_2

You replaced that with a low quality one

**Comment by ItaloKnox** [comment]
Crap, I relied too much in the autocomplete. Can you drop the right file here? Got rid of my backup.

**Comment by Kamlingen** [comment]
![end_2](https://cloud.githubusercontent.com/assets/22724316/26227657/37ddd764-3c34-11e7-9f26-0d03c7530da8.png)

**Comment by ItaloKnox** [comment]
Hoping this time there's nothing wrong with the file. It's already uploaded.

**Comment by enumag** [comment]
Most of the files don't seem to be uses in the scripts. I don't feel comfortable about removing them though. Anyway here is the list of things to be fixed:

Oni, Wata and Hima:
rename End_2.png to end_2.png
rename End_1.png to end_1.png

Tata and Mea are ok, I could fix all issues in the scripts directly.

**Comment by ItaloKnox** [comment]
In this case should I push a new patch for all of them?

**Comment by enumag** [comment]
Yeah, Oni, Wata and Hima all need an updated graphics patch. For Hima we also should do something about [this](https://github.com/07th-mod/himatsubushi/issues/17) before next release.

**Comment by ItaloKnox** [comment]
I would go with your suggestion for that. I'll push a new tag for Hima after you push the script with the menu updated.

Edit: if >> with, english sucks.

**Comment by enumag** [comment]
Done.

**Comment by ItaloKnox** [comment]
New patches and installers are ready to roll. Thanks a lot, guess we can close this now.

**Comment by enumag** [comment]
@Kamlingen Let us know if you find any more issues. Thanks for reporting.
