### ISSUE TITLE
wata_007.txt, line 3633

### ISSUE THREAD

**Issue by ideal-fire** [higurashi-mod/watanagashi#56]
OutputLine(NULL, "じゃあ、……その時にも誰かが、……『消えた』？",
		   NULL, " So... at that time, someone else... "vanished"?", Line_WaitForInput);

This line doesn't display in game because "vanished" isn't in quotation marks.
It should either be removed or fixed. I wasn't sure which one you guys wanted, so I made this issue.

**Comment by ItaloKnox** [comment]
Hey @enumag, should it be ``NULL, " So... at that time, someone else... \"vanished\"?", Line_WaitForInput);`` instead? I always forget how to use the backslash.

Edit: I'm pretty positive I got the right one so I went ahead and pushed it. I'll release a new update after you confirm it.

**Comment by enumag** [comment]
Yeah, it's correct.
