### ISSUE TITLE
Typo in the update dialogue

### ISSUE THREAD

**Issue by jwgrlrrajn** [higurashi-mod/watanagashi#57]
![image](https://cloud.githubusercontent.com/assets/13456824/26278241/37ee98f6-3d5b-11e7-8f0d-9c13972fc47a.png)
At first I thought it was a kerning issue, but I checked the wata_004.txt files in both the Scripts and Update folder, and apparently, the official script says "garner," but the update script says "gamer." I'm assuming there's no issue with just replacing the word in the script, but just to be safe, I'm putting the updated script file here instead of replacing the one in the patch.
[wata_004.txt](https://github.com/07th-mod/watanagashi/files/1016388/wata_004.txt)

**Comment by ItaloKnox** [comment]
Just pushed the update to the repo, thanks a lot. I think you can save more time just by making a pull request instead of opening an issue. It's not obligatory but think about it in case you find anything else.
