### ISSUE TITLE
MG files

### ISSUE THREAD

**Issue by Grelo** [higurashi-mod/watanagashi#59]
@enumag Can you pls look into these files if they are used? If yes ill recreate them. They are leftovers from installer after your cleaning. Will check other chapters as well.

wata_mion01
wata_mion02
wata_mion03
wata_mion04
wata_mion05
wata_rena01
wata_rena02

edit: Onikakushi and Himatsu are Ok. In Tatarigoroshi replace files with these and then its fine - 
![red](https://user-images.githubusercontent.com/22790067/27042919-b82d4036-4f98-11e7-830b-d51dd7a5f340.png)
![s_jump_back](https://user-images.githubusercontent.com/22790067/27042920-b851a5d4-4f98-11e7-8e56-8e06537667fa.png)
![up](https://user-images.githubusercontent.com/22790067/27042921-b853b1e4-4f98-11e7-987f-9eef781602f6.png)

File names: red, s_jump_back, up

**Comment by enumag** [comment]
@Grelo The wata_mion and wata_rena files are all mentioned in the scripts but they are all commented out, hence unused. We can remove them.

**Comment by enumag** [comment]
@ItaloKnox This one is for you.

1) In wata graphics patch remove files `wata_mion*` and `wata_rena*`.
2) In tata graphics patch replace files `red`, `s_jump_back` and `up` with those above.

**Comment by ItaloKnox** [comment]
Sure, I'll try to push a new build in a couple hours. Will update here when they're live.

**Comment by ItaloKnox** [comment]
I had some issues pushing the release using the terminal so it took more time than I expected. Fortunately it ended well and both updates are out. I hope no one was affected by the ~30 minutes downtime of Tata graphics.
