### ISSUE TITLE
Missing voices

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/watanagashi#60]
I think we're missing voices `s02/01/130100926` and `s02/01/130100927` [here](https://github.com/07th-mod/watanagashi/blob/master/Update/wata_011_02.txt#L4244-L4255). Can you check if they match the text and change the text accordingly if they don't?

**Comment by ItaloKnox** [comment]
Ok, so the voice ending with 26 covers lines 4244 and 4251. 

The last one is a bit more complicated, in both PS3 and PS2 we don't have the dialog before the comma. So to match it completely you should take off the ``...After the meeting was over,`` and ``……会合が終わった後、`` from the text. The rest matches perfectly.

**Comment by enumag** [comment]
Thanks. I'll fix it right away.

**Comment by enumag** [comment]
Wait I made a small mistake. We're missing `s02/01/130100927` and `s02/01/130100928` actually. 26 is used just above.

So.... 27 is "If you didn't... then there wouldn't have been any time left." and 28 is "The mayor disappeared on his way home.", right?

**Comment by ItaloKnox** [comment]
Yep, that's right. We just got the number wrong by 1. 😆
