### ISSUE TITLE
Higurashi - Watanagashi freezes during a specific scene 

### ISSUE THREAD

**Issue by StaphTouchinMeh** [higurashi-mod/watanagashi#61]
[Original Thread from Reddit](https://www.reddit.com/r/visualnovels/comments/6l5qdt/watanagashi_scene_freeze_during_a_particular_scene/)

I'm playing through Watanagashi and I finished the scene [Watangashi Spoilers] (/s "where Takano takes Shion and Keiichii to show them the tools for the ritual.") After this scene, I get to the point where I meet up with Mion, Rika and Rena and Rika asks about the performance and[ here's where my error occurs](https://my.mixtape.moe/lhlvse.mp4). I'll also show you my files, the important ones. 

* [StreamingAssets folder ](https://i.imgur.com/EN1UZ2l.png)

* [CG folder](https://i.imgur.com/YFncy4T.jpg)

* [Scripts folder](https://i.imgur.com/yOB2wnV.png)

* [SE folder](https://i.imgur.com/S3Am907.png)

~~Sorry if this is not the right subreddit to post. I was thinking of posting to the Higurashi subreddit  but that's pretty dead.~~

EDIT: forgot to add that in the video, there's no voices because i took out the voice files per a friends method but that didn't work unless im doing it wrong...

EDIT: I tried re-applying the voice and bg patches to see if that would solve but no luck

**Comment by enumag** [comment]
Check the CG/night directory if there is a file named me_si_ma_a1.png. If it is missing reapply the graphics patch with sprites. If it is there please upload file HigurashiEp02_Data/output_log.txt.

**Comment by ItaloKnox** [comment]
Your game will most likely freeze if you messed with the files and didn't make the necessary changes in the script for that. If it calls a file that doesn't exist, then it will freeze. Upload the ``output_log.txt`` so we can have a look.

**Comment by StaphTouchinMeh** [comment]
@ItaloKnox @enumag Yeah, I just checked the `me_si_ma_a1.png` and yes [its in the `CG/Night` folder.](https://i.imgur.com/AHl1Y5A.png) 

[output_log.txt](https://my.mixtape.moe/gfqhmt.txt)

**Comment by ItaloKnox** [comment]
``Could not find texture asset C:/Users/Felix/Downloads/Higurashi When They Cry Hou - Ch.2 Watanagashi/HigurashiEp02_Data/StreamingAssets\CG/night/me_si_ma_a2.png``

That's your issue. You're probably missing a few sprites, maybe try installing the graphics patch again.

**Comment by enumag** [comment]
Actually no you are not missing sprites. It seems you have outdated scripts in the Update directory. The `night/me_si_ma_a2.png` was replaced by `night/me_si_ma_a1.png` 2 months ago (because they were the same and we wanted to make the patch smaller). I recommend using the installer to get the latest version.

**Comment by StaphTouchinMeh** [comment]
Alright, thanks! I'll try the installer method!

**Comment by StaphTouchinMeh** [comment]
@enumag Just tried the installer and now when [I open up Watanagashi, it just shows a black screen.](https://i.imgur.com/cxqcpja.png) It doesn't display the menu

**Comment by ItaloKnox** [comment]
Clean your CompiledUpdateScripts folder and see if the CG folder contents looks okay. Maybe something went wrong and you just don't have all the files.

**Comment by StaphTouchinMeh** [comment]
Thanks so much, the two of you! It worked.

**Comment by ItaloKnox** [comment]
Glad to see that. Reopen the issue if you need more help!

**Comment by enumag** [comment]
@ItaloKnox Isn't the CompiledUpdateScripts directory cleaned by the installer? (It should be in my opinion.)

**Comment by ItaloKnox** [comment]
Actually it isn't because I always intended it to be used when you first installed the patch, but I implemented this later in the updater. It's a simple feature so I'll update the installers to clean them.
