### ISSUE TITLE
Phone's ringing in first chapter of watanagashi wont stop playing after installing the ADV and the ADV not yet installed correctly

### ISSUE THREAD

**Issue by gagantous** [higurashi-mod/watanagashi#62]
i have  an issue after i installed the ADV mode, the mode "wall of text" still on it... but the text got below like the ADV mode like this pic...

adn the phone wont stop ringing even after keichi hang up the phone and shion start to talk

![aasd](https://user-images.githubusercontent.com/24579576/28241446-1bdf0ef0-69c7-11e7-882a-5436a3a2b1dc.png)

**Comment by gagantous** [comment]
and at this scene, the phone still ringing

**Comment by ItaloKnox** [comment]
You're missing the ``windo_filter.png``. I'm pretty sure you should get a CG folder with this file in the patch.

Also don't forget to clean the ``CompiledUpdateScripts`` folder after installing it. But anyway, @enumag should be able to handle this if none of these are your solution.

**Comment by enumag** [comment]
What @ItaloKnox wrote is correct, I was about to write the same thing.

I'll need to look into the phone issue though.

**Comment by enumag** [comment]
Phone works fine for me. I checked the script too and it looks correct.

**Comment by gagantous** [comment]
thanks!, i had fixed that with  `windo_filter.png `. Thw file seems only replaced on `CG` folder, not `CGAlt`, 

and about the phone issue keep playing, maybe i started the game too fast after i deleted the `CompiledUpdateScripts`, so when i press ctrl to skip the scene, the compiled not yet finished compiled the update file, imo

![bare](https://user-images.githubusercontent.com/24579576/28243742-847536c4-6a08-11e7-96dc-7346ee6f96b9.png)

**Comment by enumag** [comment]
The game should not start at all until compilation is finished. If you start the game again from the beginning, does it happen again? My guess is that it was a one-time hiccup of the game engine and won't happen again.

You don't need `windo_filter.png` in `CGAlt` so don't worry about that.

**Comment by gagantous** [comment]
yep the game is work just fine, no more issue for the phone's ringing thanks for your help (y),
