### ISSUE TITLE
Possible issue in chapter 7 in ADV mode

### ISSUE THREAD

**Issue by jwgrlrrajn** [higurashi-mod/watanagashi#63]
Shortly after exploring the shed/shrine with Tomitake and Co. there's this line of narration coupled with actual dialogue, and it makes it look momentarily like Mion is narrating in third person.
![img_0794](https://user-images.githubusercontent.com/13456824/28470669-09afcbba-6e00-11e7-8ae4-5653494b007d.JPG)
Not sure if there's a better way to handle this scene, but I figured you'd want to know.

**Comment by enumag** [comment]
Personally I prefer these cases not-separated, so as it is now. But I don't feel too strongly about this so I'll leave it to @ItaloKnox to decide.

**Comment by ItaloKnox** [comment]
To be honest I also found it a little confusing. Technically isn't Keiichi the narrator (in most cases)? At least in my opinion I would take the name away from this and not change anything else. Though I also don't think this is really a big deal, so dunno if it's worth changing.

**Comment by enumag** [comment]
Or we could drop just the "Mion sighed and said," part completely. With the voices the reader will hear her sigh anyway so there is no need to mention it in the text. I actually think this is the best solution here.

**Comment by ItaloKnox** [comment]
Yep, I agree with that. Let's do this.

**Comment by jwgrlrrajn** [comment]
Now that you mention it, you could also replace "Mion sighed and said" with "\*sigh\*," in case anyone has the sounds turned off.

**Comment by enumag** [comment]
I thought about that but I don't think it's used anywhere else in Higurashi so I don't want to go that way.
