### ISSUE TITLE
Watanagashi installer being detected as a virus

### ISSUE THREAD

**Issue by dister10** [higurashi-mod/watanagashi#64]
Hi. I'm having difficulty downloading the Watanagashi installer because Google Chrome views it as a virus and refuses to let me download it. I've tried to install the patch manually but have had less success than I have with the installer for the other arcs. Please get back to me as soon as possible.

**Comment by ItaloKnox** [comment]
Unfortunately there's nothing we can do about Google Chrome. If anything, I can provide you an alternative that is far less than ideal, but might work.

Download these:
[temp.zip](https://github.com/07th-mod/watanagashi/files/1181998/temp.zip)
[install.bat](https://raw.githubusercontent.com/07th-mod/resources/master/watanagashi/install.bat)

Create a folder called ``temp`` inside your ``StreamingAssets`` folder and extract the file ``temp.zip`` inside that folder. Also copy the file ``install.bat`` to the ``temp`` folder. Your ``temp`` folder should have these files:
![nvidia share_2017-07-28_01-19-57](https://user-images.githubusercontent.com/4702556/28702374-e2b0c162-7332-11e7-85fc-f2999c9a0d5a.png)

Now run the file ``install.bat`` and see if the patch installs correctly.

I'm going to bed right now but if the issue isn't solved by the time I wake up I promise I'll do something about your case. 👍

**Comment by ItaloKnox** [comment]
By the way, if Chrome doesn't download the file ``install.bat`` automatically, click on the link with the right button and use the ``save link as...`` option. Just clearing it up in case of any doubts.

**Comment by dister10** [comment]
The alternative worked just fine. Thank you for your help

**Comment by ItaloKnox** [comment]
Glad to hear that, enjoy the game. 😄
