### ISSUE TITLE
GCensor branch progress

### ISSUE THREAD

**Issue by P-Chang** [higurashi-mod/watanagashi#65]
I started separating deleted dialog with GCensor flag in chapter2.
Probably progess confuse you, so I write progress in this issue.

If you want to edit script in progress, I will preferentially finish that script file until B progress.

If you help progress B, this DLL is useful.
If GMOD_DEBUG_MODE flag is 2, it automatically stop with GCensor branch in skip mode.

http://www.mediafire.com/file/habt3yyqwbobr95/DLL_Chapter2Chechking.rar

A.Separating and small checking(only checking crash and freeze)
B.Checking and fix completely(text flow and double quatation in English and 「」in Japanese, and sprites)
C.Finding and Adding Voice

[2017-11-08]
Progress A and B are finished. There are possibility that I failed some point.
If you find bug, I'll fix it immediately. 

[2017-12-19]
Probably there are no voice that we can find in ps2 archive.
Violence scene have many deleted one, but reaming dialogs have different reason.

wata_001.txt
- [x] A
- [x] B
- [ ] C

wata_002.txt
- [x] A
- [x] B
- [ ] C

wata_003.txt
none

wata_004.txt
- [x] A
- [x] B
- [ ] C

wata_005.txt
- [x] A
- [x] B
- [ ] C

wata_006.txt
none

wata_007.txt
- [x] A
- [x] B
- [ ] C

wata_008.txt
- [x] A
- [x] B
- [x] C

wata_009.txt
- [x] A
- [x] B
- [ ] C

wata_009_02.txt
- [x] A
- [x] B
- [ ] C

wata_010.txt
- [x] A
- [x] B
- [ ] C

wata_010_02.txt
- [x] A
- [x] B
- [x] C

wata_010_03.txt
none

wata_010_04.txt
- [x] A
- [x] B
- [x] C

wata_011.txt
All changes are improvement, I leave it.

wata_011_02.txt
- [x] A
- [x] B
- [x] C

wata_012.txt
- [x] A
- [x] B
- [ ] C

wata_012_02.txt
- [x] A
- [x] B
- [x] C

wata_012_03.txt
- [x] A
- [x] B
- [x] C

wata_ep_01.txt
none

wata_ep_02.txt
- [x] A
- [x] B
- [x] C

wata_tips_01.txt
- [x] A
- [x] B
- [ ] C

wata_tips_02.txt to wata_tips_04.txt
none

wata_tips_05.txt
- [x] A
- [x] B
- [ ] C

wata_tips_06.txt to wata_tips_09.txt
none

wata_tips_10.txt
- [x] A
- [x] B
- [ ] C

wata_tips_11.txt to wata_tips_12.txt
none

wata_tips_13.txt
- [x] A
- [x] B
- [ ] C

wata_tips_14.txt to wata_tips_21.txt
none

wata_tips_22.txt
- [x] A
- [x] B
- [ ] C

wata_tips_23.txt
none

wata_tips_24.txt
- [x] A
- [x] B
- [ ] C

**Comment by enumag** [comment]
Nice. If you find some recurring mistakes that could be fixed everywhere with a script, let me know and I'll write it.

**Comment by enumag** [comment]
@P-Chang I see you're adding some missing voices (for example [here](https://github.com/07th-mod/watanagashi/commit/0e1e9303a40bafac8abcf91984243a18528af58d)). Did you know that when you add voices to the scripts you should add the voice files to this repository too? This way the actual files will be missing.

You don't need to worry about about any voices you didn't add in the past though. I have a script to detect the missing ones.

**Comment by enumag** [comment]
@P-Chang Also please check the "Known issues" section in the readme. You might have fixed some of them.

**Comment by P-Chang** [comment]
@enumag 
Added voice are nearly 100. so I didn't add these to repository.
I also have own voice file detector, so I can upload it in somewhere for voice patch include it.

Although, I'll implement it in my symlink tool after finish some bug track. so if you or @ItaloKnox will use symlink with my tool. voice can be exported with save directory structure.

And I can't read php especially MySQL , so I can't understand what your tool do.
So, my tools may be not needed.
 
files location that I added have different directory structure with ps2 resource archive(remade these same as ps3 directory like ps2 files in tata). 
Can your scripts detect these correctly?

>  Also please check the "Known issues" section in the readme. You might have fixed some of them.

OK, I'll fix it soon. and is it true that line that was wrote in "Know Issues" point to line of previsou patch?

**Comment by enumag** [comment]
Yeah if there are this many, it's indeed better to add them to the voice patch instead. :+1:

My script should be able to handle that. It just takes the path from PlaySE (I need to update it to use PlayVoice but that's trivial) and looks if that file exists.

Watanagashi was not updated in a long time so while the lines might not be completely exact, they should match in most cases.

**Comment by ItaloKnox** [comment]
If you guys can manage to pack them together I can push everything into the voice patches today. Or I can use @enumag's script to do this job, I just hope we can cut out the parts where it deals with the graphics.

**Comment by P-Chang** [comment]
Graphic update is not needed as much as I checked.

**Comment by enumag** [comment]
@ItaloKnox The main compilation command just calls some subtasks so skipping those related to graphics is not a problem. Missing files detection probably deals with both voices and graphics but I can surely simplify that. Our graphics zips are in a good shape now so I'll refactor or remove most of that stuff for Tsumi.

**Comment by ItaloKnox** [comment]
I went ahead and merged @P-Chang changes and also did the same to every other change that was packed with our scripts currently. Also changed the folder names to ``voice`` so it's one step less in the installation now.
