### ISSUE TITLE
Can't progress after a line of dialog

### ISSUE THREAD

**Issue by Oyashirox** [higurashi-mod/watanagashi#67]
Hi,

On chapter 12, I can't continue after a line of dialog. The problem seems to be at that line : https://github.com/07th-mod/watanagashi/blob/5abeb49be1a16a9d17878441673f51ffcea1a2d2/dev/Update%20(voice%20only)/wata_012_02.txt#L2379

`PlaySE(4, "S02/03/1303003446, 128, 64);` should be `PlaySE(4, "S02/03/130300346", 128, 64);` (Wrong file name and missing `"`)

I tried changing the filename without success, but as I am writing this, I just noticed the missing quote, so I'll wait the game to reinstall and try again.

**Comment by ItaloKnox** [comment]
You are correct, I don't know how that got past testing. I'll be pushing an update in a bit.

**Comment by Oyashirox** [comment]
I made pull request https://github.com/07th-mod/watanagashi/pull/68 to fix this.

**Comment by ItaloKnox** [comment]
I just noticed you found this mistake in the voices-only patch. We don't usually touch these after we make the graphics patch, but since I was already on this I merged the PR and fixed the other two that you didn't see. 👍
