### ISSUE TITLE
Can't download the patch

### ISSUE THREAD

**Issue by TaylorHyuuga** [higurashi-mod/watanagashi#72]
When I try and download it, it gives me an error message saying it's "dangerous, so Chrome has blocked it". I also tried the manual downloads, but they all gave me a "error-forbidden". Anyone know any way to fix it?

**Comment by TaylorHyuuga** [comment]
Okay, I was able to get the manual download to work for all parts, but now it's not responding when I try to open it. I'll try opening it again tomorrow, and try and redownload everything if it still doesn't work then. If it doesn't work after I redownload anything, then I may need help

**Comment by TaylorHyuuga** [comment]
Alright, I was able to get it working,

**Comment by ItaloKnox** [comment]
That's good, I think something strange happened on Github while you were trying to download the files. I checked them and they are working well right now.
