### ISSUE TITLE
AVG identifies auto-installer as a trojan?

### ISSUE THREAD

**Issue by HarujiSan** [higurashi-mod/watanagashi#73]
To be more specific, I can download the auto-installer from any browser except Chrome, which blocks it. I downloaded it and scanned it, and AVG said it was fine. But when I ran the installer, it stopped not long after the CMD window came up and said it had detected a trojan. The file it quarantined was called something like "Trojan-gen3" or something like that.
I've installed the Onikakushi-hen and Tatarigoroshi-hen patches with zero problems and they work beautifully!
Any idea what's going on with that file? I paid $1500 for this computer, so I'm pretty paranoid about downloading anything, heheh.
Thanks!

**Comment by ItaloKnox** [comment]
As explained in the guide:
> as reported, some antivirus softwares might warn you about the installer. **This is a false positive, and it happens because the installer runs a batch file (that results in the CMD window opening to download and install the patch)**. The installer code can be freely accessed in our Resource repository and is clean of viruses.

The code for the Watanagashi installer [can be found here](https://github.com/07th-mod/resources/blob/master/watanagashi/install.bat) and reviewed in case you still have doubts about it. [This article in the developer wiki](https://github.com/07th-mod/higurashi-dev-guides/wiki/technical-details) also explains the installer in detail.

In any case, if you are really paranoid about this you can just follow the guide and install the patch using the manual installation method, which should be very simple to follow.

**Comment by HarujiSan** [comment]
Alrighty, thanks for the links! I'll go ahead and install.
Thanks again!

**Comment by ItaloKnox** [comment]
No problem, I hope you don't have any issues with it.
