### ISSUE TITLE
Tips Menu arrows

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#74]
I don't think that's... normal?
![image](https://user-images.githubusercontent.com/12663654/39985462-0263b9cc-575f-11e8-815a-11c8df27a95d.png)

**Comment by enumag** [comment]
Nice one. :smile: 

@InochiPM Can you fix this?

**Comment by InochiPM** [comment]
What Tips Menu is this for?

**Comment by enumag** [comment]
FIxed.
