### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#75]
https://github.com/07th-mod/watanagashi/blob/f02f4ba0e4f073d853d0838fa0f93a935c587d01/Update/zwata_002_vm00_n02.txt#L65

This line says "I" when it's Rena who speaks. Probably a mistake in translation as my poor attempt to understand the original seemed to show it's indeed Rena referring to Keiichi(also, what a meaning, lol).

**Comment by Norgus** [comment]
I read over the section, and you're definitely right on this.

Fixed in this commit: https://github.com/07th-mod/watanagashi/commit/abe00721d75fefbfa3efc3822467b4e0b5ac8f94
