### ISSUE TITLE
Typo in Unlocking screen

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#76]
![image](https://user-images.githubusercontent.com/12663654/40058310-1754d6f2-5851-11e8-8ebe-d4fa7185362b.png)

It sure hasen't.

**Comment by orian34** [comment]
also, the title in the menu is "It hasn't been a while"

**Comment by enumag** [comment]
cc @InochiPM

**Comment by orian34** [comment]
There was another typo in the screen after day 11. I think I missed the timing to screenshot it, but I remember reading "At the Suzu Mahjon Parlor" while the Tip title in the menu is "At the Suzu Mahjong Parlor."

That was because I didn't knew Mahjon existed as a word that it was imprinted in my mind. I'm sure there is a typo. I don't know where to check though.(damn, those unlock screens are tough to check out when you don't think about them, cause they just pass like that, zoom!)
