### ISSUE TITLE
Missing in day selection.

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#82]
The last day is missing the "Day" in it.
![image](https://user-images.githubusercontent.com/12663654/40878799-77280e3e-6696-11e8-9042-90730b0e4784.png)

**Comment by enumag** [comment]
Some info from Doddler:

it's on a prefab called ChapterJump on a component called ChapterJumpButton

https://puu.sh/Barkh/0b569e0ec9.png

I guess in theory you could modify ChapterJumpButton (in the DLL), it should have the old name available in the Start or Awake function when it's created.

**Comment by enumag** [comment]
Fixed for next release.
