### ISSUE TITLE
Missing "

### ISSUE THREAD

**Issue by ghost** [higurashi-mod/watanagashi#84]
![20180613170329_1](https://user-images.githubusercontent.com/40277497/41434271-7505f2cc-701b-11e8-910c-0624f2dda1ed.jpg)
![20180614212625_1](https://user-images.githubusercontent.com/40277497/41434280-7f1967bc-701b-11e8-8e41-089ecc6f13b4.jpg)

**Comment by orian34** [comment]
already fixed.
