### ISSUE TITLE
Teacher's curry rant in Ch 3 goes off screen in English + ADV mode

### ISSUE THREAD

**Issue by TellowKrinkle** [higurashi-mod/watanagashi#88]
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/3315070/44194988-53ecd480-a0fd-11e8-8613-3f67f7db575b.png">
Text is from wata_003.txt:L4712, Here's a save file near the location:

[save002.dat.zip](https://github.com/07th-mod/watanagashi/files/2292803/save002.dat.zip)

**Comment by orian34** [comment]
It's something that is written in the middle of the screen, we haven't got
that feature yet though.

**Comment by enumag** [comment]
Yeah for now this needs to be fixed by lower font size in ADV mode.

I fixed it in https://github.com/07th-mod/watanagashi/commit/4188ddf4fc11c823547cceaa569c7b80810c9077.
