### ISSUE TITLE
Audio / English Name Mismatch

### ISSUE THREAD

**Issue by TellowKrinkle** [higurashi-mod/watanagashi#89]
At [this line](https://github.com/07th-mod/watanagashi/blob/2bfa54512030785c95dfa221250c3dfc8b528191/Update/wata_tips_22.txt#L278), Ooishi refers to someone named 山海.  MangaGamer translates this as "Yamaumi", which doesn't match with the PS3 audio (at `ps3/s20/11/440700177.ogg`), which reads it as "Sankai"

There's also a kun-san mismatch [here](https://github.com/07th-mod/watanagashi/blob/2bfa54512030785c95dfa221250c3dfc8b528191/Update/wata_007.txt#L1968)

**Comment by InochiPM** [comment]
Thats actually amusing, They literally used the separate kanji names then stuck them together. They should of translated it to "The Mountains and Seas" since thats what it actually means and isn't a proper name?

**Comment by TellowKrinkle** [comment]
It has `さん` on it so it's definitely a name (I just left it out here because it wasn't the part with a mismatch)

**Comment by enumag** [comment]
uuh... @Norgus ? :-D

**Comment by InochiPM** [comment]
So from looking around with the info given, i could only find one Sankai, Sankai (山塊) is the chief of the riot police of Okinomiya. But the second kanji is off, where the the closest i could get to "Yamaumi" was Yamaoki Kaoru (山沖 薫) So either mangagamer got the second kanji wrong? or they are making up their own characters at this point lmao 
-EDIT-
or it could be the Yamainu (山狗)? the second kanji resembles the the kanji to Umi (海)

**Comment by enumag** [comment]
I guess we should check the PS3 script then. I'll do it when I get home unless someone beats me to it.

**Comment by TellowKrinkle** [comment]
It's used [here](https://github.com/07th-mod/himatsubushi/blob/ab4cf3e30cb11241b3d4b99b113ed23c633d0522/dev/Scripts/hima_001.txt#L3147) and [here](https://github.com/07th-mod/tsumihoroboshi/blob/f0e300c5ec67e845ed4763734542343e5cf60090/Update/_tsum_023_1.txt#L1229), both with the 山海 spelling

**Comment by Norgus** [comment]
I couldn't find 山塊 anywhere in the scripts on my PC or the PS3 script, and it seems the guy's name is consistently 山海, so I suspect it should be "Sankai" and "Yamaumi" is a mistaken reading from having only the text.

**Comment by InochiPM** [comment]
Huh thats really weird, Theres no record of a character named with those kanji other than the "Sankai" i found while looking which is the name of the Chief of the riot police, who is this mystery man ?

**Comment by Norgus** [comment]
What mystery man? I think it's just one Sankai-san and no "Yamaumi" exists.

edit: did not mean to click "Close issue"... sorry

**Comment by TellowKrinkle** [comment]
I'm going to guess `山塊` just a misspelling on the English wiki.  Searching google for `ひぐらしのなく頃に　"山塊"` gets me nothing while searching `ひぐらしのなく頃に　"山海"` gets results that are at least related to the game, including [this random wiki page](http://www.wikihouse.com/higurasi/index.php?%A4%BD%A4%CE%C2%BE) listing them under "Other Subcharacters"
Edit: It also calls them `県警暴対部長` which seems like it would match with `Chief of the riot police`

**Comment by enumag** [comment]
@tellowkrinkle How should we fix it then in your opinion? Can you open a pull request?

**Comment by TellowKrinkle** [comment]
Personally I would just edit the script, considering it a translation mistake.  Are there any other things that you think would make sense?

**Comment by enumag** [comment]
Not really. Just change the script as you see fit.

**Comment by TellowKrinkle** [comment]
All right, does that seem reasonable?

**Comment by enumag** [comment]
Yeah I think so. Thanks!
