### ISSUE TITLE
Wrong translation in day 5?

### ISSUE THREAD

**Issue by vstax** [higurashi-mod/watanagashi#91]
A really minor issue and I might be wrong about it, but shouldn't this line https://github.com/07th-mod/watanagashi/blob/v4.3.0/Update/wata_005.txt#L7694 be something along "Even if Rena gave it to you... that wouldn't solve anything." ?
Currently it just doesn't make much sense.

**Comment by enumag** [comment]
@Norgus Can you check this please?

**Comment by Norgus** [comment]
It is definitely wrong, and it's Rena speaking. She's saying "It wouldn't really help (wouldn't solve anything), even if I gave you the doll I got, would it."

It does make me a little sad when a line is this radically wrong. Committed a fix. 4f330fa6bbb95c93360d23dafb836bc418012c20

**Comment by orian34** [comment]
Seems to be a subject confusion. The sentence makes sense if it was Mion speaking. Except it's Rena here.

It's more of an oversight mistake than a really badly translated line.

**Comment by enumag** [comment]
I think it was the translator's choice to translate this in a way where Mion is the speaker rather than Rena. Remember that the translator was not constrained by voices so choosing to change the speaker was an option.

**Comment by orian34** [comment]
Might even be the opposite and the console changed the person, while MG followed the original script.
Though I have no idea.

**Comment by Norgus** [comment]
I mean, translating it as literally as I dare, it's 

"even if (I) give the one received by Rena, that doesn't solve anything, does it."

Which makes no sense in any context for Mion to be saying. It's also fairly common for Rena to refer to herself by her own name,, so I'd say the speaker is clear enough.

**Comment by vstax** [comment]
What a heated discussion :)
Out of curiosity I dumped data0100.arc/wata_005 from very first MG release (not even "Editorashi") and these lines were translated like
```
"Did you want that doll?"

........................

"It's not going to solve anything... If I give you the one I got from him, right...?"

"......Right..."
```
So the old translator didn't make a mistake here
