### ISSUE TITLE
Spaces missing in text.

### ISSUE THREAD

**Issue by dongmaster** [higurashi-mod/watanagashi#96]
Close to the start of chapter 4 in Watanagashi, there's a part where there's missing spaces in the text. 
The text is: "They also pile futons up on the altar.The Watanagashi is a festival that happens at the shrine on a sunday every June.It's very lively!"

I found the file and lines where the text occurrs: https://github.com/07th-mod/watanagashi/blob/229d430d633867008dfb8de29bd7b2b1eb44d43b/Update/zwata_004_vm0x_n01.txt#L58-L68

**Comment by orian34** [comment]
👌  fixed. Thanks for the report
